# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)

In [15]:
print('Dimension (number of axes): ', np.ndim(A))
print('Shape: ', np.shape(A))
print('Size: A has: ', np.size(A), ' elements')
print('Datatype: ', A.dtype)

Dimension (number of axes):  2
Shape:  (3, 5)
Size: A has:  15  elements
Datatype:  int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [17]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [21]:
print('Elementwise subtraction\n', B - C)
print('\nElementwise multiplication\n', B * C)
print('\nMatrix multiplication\n', B @ C)

Elementwise subtraction
 [[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]

Elementwise multiplication
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix multiplication
 [[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [11]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print('Exponentiate each number elementwise:\n', np.exp(B))

print('\nMinimum value in the whole matrix: ', np.min(B))

print('\nMinimum value in each row:\n', np.min(B, axis=1))

print('\nMinimum value in each column:\n', np.min(B, axis=0))

print('\nIndex value for the minimum value in the whole matrix: ', np.argmin(B))

print('\nIndex value for the minimum value in each row:\n',  np.argmin(B, axis=1))

print('\nSum for all elements: ', np.sum(B))

print('\nMean for each column:\n', np.mean(B, axis=0))

print('\nMedian for each column:\n', np.median(B, axis=0))

Exponentiate each number elementwise:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix:  1

Minimum value in each row:
 [1 4 7]

Minimum value in each column:
 [1 2 3]

Index value for the minimum value in the whole matrix:  0

Index value for the minimum value in each row:
 [0 0 0]

Sum for all elements:  45

Mean for each column:
 [4. 5. 6.]

Median for each column:
 [4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [39]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [41]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [ ]:
A

In [44]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [48]:
for i in A.flat:
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [37]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


creates a 1-dimensional array of integers from 0 to 29.
Reshapes the array into a 3-dimensional array with: 2 blocks (first axis) 3 rows in each block (second axis)
Axis 2: Divides each row into 5 columns.

In [61]:
print('Shape for axis=0, has ', b.shape[0], ' blocks.')
print('Shape for axis=1, has ', b.shape[1], ' rows in each block.')
print('Shape for axis=2, has ', b.shape[2], ' elements in each row.')

Shape for axis=0, has  2  blocks.
Shape for axis=1, has  3  rows in each block.
Shape for axis=2, has  5  elements in each row.


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [79]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

if m1.shape == m2.shape:
    print('m1 and m2 has same shape! We can add. m1 + m2 = ', m1 + m2)
elif not m1.shape == m2.shape:
    print('m1 and m2 has not same shape!')
print('m1 shape: ', m1.shape) # Shape (2, 2)
print('m2 shape: ', m2.shape) # Shape (2, 1)

[[2 3]
 [4 5]]
m1 and m2 has not same shape!
m1 shape:  (2, 2)
m2 shape:  (2,)


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [81]:
v1 = np.array([1, 2, 3])
print(v1 + 1) 

[2 3 4]


In [83]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [81]:
def add_mult_matrices(m1, m2, operation):
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise ValueError('Both matrices must be of type: numpy.ndarray!')
    # Check if operation is add or multiply, or something else.
    if operation not in ['add', 'multiply']:
        raise ValueError("Operation must be 'add' or 'multiply'.")
    if operation == 'add':
        if m1.shape != m2.shape:
            raise ValueError("Matrices must have the same size for addition.")
        print('matrix_1 + matrix_2\n', m1 + m2)
    if operation == 'multiply':
        if m1.shape[1] != m2.shape[0]:
            raise ValueError('Number of columns in the first matrix must equal number of rows in the second matrix for multiplication.')
        print('\nmatrix_1 @ matrix_2\n', m1 @ m2)

# Test add
M1 = np.array([[1,2,3]]) 
M2 = np.array([[4,5,6]])
add_mult_matrices(M1, M2, 'add')

# test multiply       
M1 = np.array([[1, 2, 3], [4, 5, 6]])
M2 = np.array([[1, 2],[3, 4],[5, 6]])
test1 = add_mult_matrices(M1, M2,'multiply')

matrix_1 + matrix_2
 [[5 7 9]]

matrix_1 @ matrix_2
 [[22 28]
 [49 64]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [111]:
x = np.array([4, 3])

In [177]:
X = np.array([[4, 3]]) # Hjälpfunktion med extra hakar för att bättre kunna illustrera vissa exempel.
print('a) x dimension är: ', X.shape) # använde dubbla hakar för att tydliggöra
print('\nb) 5x = ', 5 * x)
print('\nc) 3x = ', 3 * x)
print('\nd) 5x + 3x =', 5 * x + 3 * x)
print('\ne) 8x = ', 8 * x)
print('\nf) 4x - x = ', 4 * x - x)
print('\ng) xT = ', X.T.shape) # Använde dubbla hakar på denna med för att tydliggöra
print('\nh) Är x + xT definierat?\n', X.shape , X.T.shape) # Även denna med extra hakar.
print('Svar: Nej x är en (1x2)-vektor och x.T är en (2x1)-vektor, vilket reulterar till att x + xT inte är definierat.\n')
print('\ni)Beräkna ∥x∥. Svar: Normen av x = ', np.linalg.norm(x))

a) x dimension är:  (1, 2)

b) 5x =  [20 15]

c) 3x =  [12  9]

d) 5x + 3x = [32 24]

e) 8x =  [32 24]

f) 4x - x =  [12  9]

g) xT =  (2, 1)

h) Är x + xT definierat?
 (1, 2) (2, 1)
Svar: Nej x är en (1x2)-vektor och x.T är en (2x1)-vektor, vilket reulterar till att x + xT inte är definierat.


i)Beräkna ∥x∥. Svar: Normen av x =  5.0


Uppgifter 10.1.2

In [179]:
v = np.array([3, 7, 0, 11]).reshape(-1, 1)

In [205]:
print('a)\n', v.shape)
print('\nb) 2v = \n', 2 * v)
print('\nc) 5v + 2v = \n', 5*v + 2*v)
print('\nd) 4v - 2v = \n', 4*v - 2*v)
print('\ne) vT = ', v.T, ' dimension efter transponeringen = ', v.T.shape)
print('\nf) ∥v∥ är ungefär ', np.linalg.norm(v))

a)
 (4, 1)

b) 2v = 
 [[ 6]
 [14]
 [ 0]
 [22]]

c) 5v + 2v = 
 [[21]
 [49]
 [ 0]
 [77]]

d) 4v - 2v = 
 [[ 6]
 [14]
 [ 0]
 [22]]

e) vT =  [[ 3  7  0 11]]  dimension efter transponeringen =  (1, 4)

f) ∥v∥ är ungefär  13.379088160259652


Övningsuppgifter 10.1.3

In [217]:
v1 = np.array([4, 3, 1, 5])
v2 = np.array([2, 3, 1, 1])

In [221]:
print('a)', np.linalg.norm(v1))
print('b', np.linalg.norm(v1 - v2))

a) 7.14142842854285
b 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [245]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E =  np.array([[1],[2]])
I =  np.array([[1, 0], [0, 1]])

array([[1, 0],
       [0, 1]])

In [279]:
print('\na) 2A\n', 2 * A)
print('\nb) B - 2A\n', B - 2 * A )
print('\nc) 3C - 2E\n', 3 * C - 2 * E)
print('\nd) 2D - 3C\n', 2 * D - 3 * C)
print('\ne) DT + 2D\n', D.T + 2 * D)
print('\nf) 2CT - 2DT\n', 2 * C.T - 2 * D.T)
#print('\ng) AT -B\n', A.T - B) 
print('\ng) Är ej definierat.')
#print('\nh) AC\n', A * C) Är ej definierad
print('\nh) Är ej definierat.')
print('\ni) CD\n', np.dot(C, D))
print('\nj) CB\n', np.dot(C, B))
print('\nk) CI\n', np.dot(C, I))
print('\nl) ABT\n', np.dot(A, B.T))


a) 2A
 [[ 4  2 -2]
 [ 2 -2  2]]

b) B - 2A
 [[ 0 -4  3]
 [ 0 -2 -4]]

c) 3C - 2E
 [[ 1  4]
 [ 2 -1]]

d) 2D - 3C
 [[3 2]
 [2 3]]

e) DT + 2D
 [[ 9 12]
 [12  9]]

f) 2CT - 2DT
 [[-4 -4]
 [-4 -4]]

g) Är ej definierat.

h) Är ej definierat.

i) CD
 [[11 10]
 [10 11]]

j) CB
 [[  8 -10  -3]
 [ 10  -8   0]]

k) CI
 [[1 2]
 [2 1]]

l) ABT
 [[5 2]
 [7 4]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [281]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [283]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [285]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


In [303]:
def is_view_or_copy(a, b):
    if a is b:
        return "same object"  
    elif b.base is a:
        return "view"  
    else:
        return "copy"  

v1 = np.array([1, 2, 3])
v2_view = v1[1:]
v2_copy = v1.copy()

print(is_view_or_copy(v1, v2_view))  # "view"
print(is_view_or_copy(v1, v2_copy))  # "copy"
print(is_view_or_copy(v1, v1))       # "same object"


view
copy
same object
